import catalogJson from './catalog/catalog.json';
import {
  priceFor,
  toSummary,
  type Operation,
  type Property,
  type PropertySummary,
  type PropertyType,
} from '@/domain/property';
import {
  DEFAULT_PAGE_SIZE,
  compareBySort,
  matchesQuery,
  type SearchQuery,
  type SearchResult,
} from '@/domain/search';
import type {
  CatalogFacets,
  CityFacet,
  NeighborhoodFacet,
  PropertyRepository,
  TypeFacet,
} from './property-repository';
import { listingPhotos } from '@/lib/local-media';
import { DEVELOPMENT_SEEDS } from '@/data/developments';
import { manualListings } from '@/data/manual-listings';

/**
 * How many listings the site actually publishes.
 *
 * The Conceitto is being shown a model of the site before deciding whether to
 * close, so the demo runs on a handful of real listings instead of all 1498:
 * a catalog someone can read end to end, and a build that finishes in seconds.
 *
 * This is the only number to change. Raise it to widen the demo, or set it to
 * `Infinity` to publish the whole synced catalog when the deal is signed.
 */
const CATALOG_LIMIT = 10;

/**
 * Picks the demo slice.
 *
 * Three things have to hold at any limit. A listing someone bothered to
 * photograph is in, always — dropping a file into `public/imagens/imoveis/`
 * has to be enough to see it on the site, with no second step. The launch
 * pages borrow price, broker and photography from specific listings, so those
 * are kept too. And sale outnumbers rental in the catalog roughly six to one,
 * so a plain "first N" would leave the Alugar filter empty — the fill
 * alternates between the two instead.
 */
function demoSlice(all: readonly Property[]): readonly Property[] {
  if (all.length <= CATALOG_LIMIT) return all;

  const launchCodes = DEVELOPMENT_SEEDS.map((seed) => seed.listingCode).filter(
    (code): code is string => code !== null,
  );

  const chosen = all.filter(
    (property) => property.photos.length > 0 || launchCodes.includes(property.code),
  );
  const taken = new Set(chosen.map((property) => property.code));

  const byEditorialWeight = (a: Property, b: Property): number => {
    if (a.isFeatured !== b.isFeatured) return a.isFeatured ? -1 : 1;
    if (a.isExclusive !== b.isExclusive) return a.isExclusive ? -1 : 1;
    return b.publishedAt.localeCompare(a.publishedAt);
  };

  const rest = all
    .filter((property) => !taken.has(property.code))
    .sort(byEditorialWeight);
  // A listing offered both ways sits in both queues; `taken` keeps it single.
  const queues: Record<Operation, Property[]> = {
    venda: rest.filter((property) => property.operations.includes('venda')),
    locacao: rest.filter((property) => property.operations.includes('locacao')),
  };

  // Rental goes first: what is already in `chosen` leans towards sale.
  let turn: Operation = 'locacao';
  while (chosen.length < CATALOG_LIMIT) {
    const next = queues[turn].shift();
    turn = turn === 'venda' ? 'locacao' : 'venda';
    if (!next) {
      if (queues.venda.length === 0 && queues.locacao.length === 0) break;
      continue;
    }
    if (taken.has(next.code)) continue;
    taken.add(next.code);
    chosen.push(next);
  }

  return chosen;
}

/**
 * The synced catalog is generated by `scripts/sync-catalog.mjs` from the data
 * MSYS already publishes, so it is trusted at the boundary and cast once here.
 */
const SYNCED = catalogJson as unknown as readonly Property[];

/**
 * Photography is re-pointed at this repository on the way out.
 *
 * The site no longer renders the MSYS S3 bucket: images are supplied as files
 * under `public/imagens/imoveis`, keyed by listing code. Doing the swap here,
 * once, means every consumer — cards, gallery, Open Graph, JSON-LD, launch
 * pages — follows without knowing where photos come from.
 */
const SYNCED_WITH_LOCAL_MEDIA: readonly Property[] = SYNCED.map((property) => ({
  ...property,
  photos: listingPhotos(property.code).map((photo) => ({
    ...photo,
    alt: photo.alt || `${property.title} — ${property.address.neighborhood}`,
  })),
  // The broker headshot is hosted on the same S3 bucket, so it goes too. Both
  // contact cards already fall back to the agent's initial.
  agent: property.agent ? { ...property.agent, photoUrl: null } : null,
}));

/**
 * What the site publishes: the demo slice of the synced feed, plus everything
 * the panel has registered.
 *
 * Computed per call rather than once at module load, because a listing created
 * in `/sistema` has to appear without restarting the server. The synced side is
 * the expensive part and it is prepared once, above.
 */
function catalog(): readonly Property[] {
  const manual = manualListings();
  if (manual.length === 0) return demoSlice(SYNCED_WITH_LOCAL_MEDIA);

  // Newest first, and never subject to the demo cap: someone registered it on
  // purpose, so hiding it behind a limit would read as the form having failed.
  const codes = new Set(manual.map((property) => property.code));
  return [
    ...manual,
    ...demoSlice(SYNCED_WITH_LOCAL_MEDIA).filter(
      (property) => !codes.has(property.code),
    ),
  ];
}

function indexByCode(): Map<string, Property> {
  return new Map(catalog().map((property) => [property.code, property]));
}

function paginate<T>(items: readonly T[], page: number, pageSize: number): SearchResult<T> {
  const total = items.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const safePage = Math.min(Math.max(1, page), totalPages);
  const start = (safePage - 1) * pageSize;
  return {
    items: items.slice(start, start + pageSize),
    total,
    page: safePage,
    pageSize,
    totalPages,
  };
}

function countBy<T, K extends string>(
  items: readonly T[],
  key: (item: T) => K,
): Map<K, number> {
  const counts = new Map<K, number>();
  for (const item of items) {
    const k = key(item);
    counts.set(k, (counts.get(k) ?? 0) + 1);
  }
  return counts;
}

class CatalogRepository implements PropertyRepository {
  async search(query: SearchQuery): Promise<SearchResult<PropertySummary>> {
    const filtered = catalog().filter((property) => matchesQuery(property, query)).sort(
      compareBySort(query.sort, query.operation),
    );
    const page = paginate(filtered, query.page, DEFAULT_PAGE_SIZE);
    return { ...page, items: page.items.map(toSummary) };
  }

  async findByCode(code: string): Promise<Property | null> {
    return indexByCode().get(code) ?? null;
  }

  /**
   * Same city first, then same type, closest price. Keeps the visitor moving
   * instead of dead-ending on a listing that does not fit.
   */
  async findSimilar(property: Property, limit: number): Promise<readonly PropertySummary[]> {
    const operation: Operation = property.operations[0] ?? 'venda';
    const reference = priceFor(property.pricing, operation);

    const scored = catalog().filter(
      (candidate) =>
        candidate.code !== property.code && candidate.operations.includes(operation),
    ).map((candidate) => {
      let score = 0;
      if (candidate.address.citySlug === property.address.citySlug) score += 4;
      if (candidate.address.neighborhoodSlug === property.address.neighborhoodSlug) score += 3;
      if (candidate.type === property.type) score += 3;
      const candidatePrice = priceFor(candidate.pricing, operation);
      if (reference !== null && candidatePrice !== null) {
        const delta = Math.abs(candidatePrice - reference) / reference;
        if (delta <= 0.25) score += 2;
        else if (delta <= 0.5) score += 1;
      }
      // A photographed listing wins a tie, but never excludes the rest — the
      // photo folders start empty and the block has to render regardless.
      if (candidate.photos.length > 0) score += 1;
      return { candidate, score };
    });

    return scored
      .filter((entry) => entry.score > 0)
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((entry) => toSummary(entry.candidate));
  }

  async featured(limit: number): Promise<readonly PropertySummary[]> {
    const ranked = [...catalog()].sort((a, b) => {
      // Photography first when it exists, then the editorial flags. Sorting
      // rather than filtering keeps the block full while the folders are bare.
      const photos = Math.min(b.photos.length, 4) - Math.min(a.photos.length, 4);
      if (photos !== 0) return photos;
      if (a.isFeatured !== b.isFeatured) return a.isFeatured ? -1 : 1;
      if (a.isExclusive !== b.isExclusive) return a.isExclusive ? -1 : 1;
      return (b.pricing.salePrice ?? 0) - (a.pricing.salePrice ?? 0);
    });
    return ranked.slice(0, limit).map(toSummary);
  }

  async facets(operation: SearchQuery['operation']): Promise<CatalogFacets> {
    const pool = catalog().filter((property) => property.operations.includes(operation));

    const cityCounts = countBy(pool, (property) => property.address.citySlug);
    const cityNames = new Map(pool.map((p) => [p.address.citySlug, p.address.city]));
    const cities: CityFacet[] = [...cityCounts.entries()]
      .map(([slug, count]) => ({ slug, name: cityNames.get(slug) ?? slug, count }))
      .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, 'pt-BR'));

    const neighborhoodKey = (p: Property) =>
      `${p.address.citySlug}::${p.address.neighborhoodSlug}`;
    const neighborhoodCounts = countBy(pool, neighborhoodKey);
    const neighborhoodNames = new Map(
      pool.map((p) => [neighborhoodKey(p), p.address.neighborhood]),
    );
    const neighborhoods: NeighborhoodFacet[] = [...neighborhoodCounts.entries()]
      .map(([key, count]) => {
        const [citySlug, slug] = key.split('::');
        return { slug, citySlug, name: neighborhoodNames.get(key) ?? slug, count };
      })
      .filter((facet) => facet.slug.length > 0)
      .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, 'pt-BR'));

    const typeCounts = countBy(pool, (property) => property.type);
    const types: TypeFacet[] = [...typeCounts.entries()]
      .map(([type, count]) => ({ type: type as PropertyType, count }))
      .sort((a, b) => b.count - a.count);

    const features = [...new Set(pool.flatMap((property) => property.features))].sort(
      (a, b) => a.localeCompare(b, 'pt-BR'),
    );

    const prices = pool
      .map((property) => priceFor(property.pricing, operation))
      .filter((price): price is number => price !== null);

    return {
      cities,
      neighborhoods,
      types,
      features,
      priceRange: {
        min: prices.length > 0 ? Math.min(...prices) : 0,
        max: prices.length > 0 ? Math.max(...prices) : 0,
      },
      total: pool.length,
    };
  }

  async count(): Promise<number> {
    return catalog().length;
  }

  async allSummaries(): Promise<readonly PropertySummary[]> {
    return catalog().map(toSummary);
  }
}

export const propertyRepository: PropertyRepository = new CatalogRepository();
