import catalogJson from './catalog/catalog.json';
import {
  priceFor,
  toSummary,
  type Operation,
  type Property,
  type PropertySummary,
  type PropertyType,
} from '@/domain/property';
import {
  DEFAULT_PAGE_SIZE,
  compareBySort,
  matchesQuery,
  type SearchQuery,
  type SearchResult,
} from '@/domain/search';
import type {
  CatalogFacets,
  CityFacet,
  NeighborhoodFacet,
  PropertyRepository,
  TypeFacet,
} from './property-repository';

/**
 * The synced catalog is generated by `scripts/sync-catalog.mjs` from the data
 * MSYS already publishes, so it is trusted at the boundary and cast once here.
 */
const CATALOG = catalogJson as unknown as readonly Property[];

const byCode = new Map(CATALOG.map((property) => [property.code, property]));

function paginate<T>(items: readonly T[], page: number, pageSize: number): SearchResult<T> {
  const total = items.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const safePage = Math.min(Math.max(1, page), totalPages);
  const start = (safePage - 1) * pageSize;
  return {
    items: items.slice(start, start + pageSize),
    total,
    page: safePage,
    pageSize,
    totalPages,
  };
}

function countBy<T, K extends string>(
  items: readonly T[],
  key: (item: T) => K,
): Map<K, number> {
  const counts = new Map<K, number>();
  for (const item of items) {
    const k = key(item);
    counts.set(k, (counts.get(k) ?? 0) + 1);
  }
  return counts;
}

class CatalogRepository implements PropertyRepository {
  async search(query: SearchQuery): Promise<SearchResult<PropertySummary>> {
    const filtered = CATALOG.filter((property) => matchesQuery(property, query)).sort(
      compareBySort(query.sort, query.operation),
    );
    const page = paginate(filtered, query.page, DEFAULT_PAGE_SIZE);
    return { ...page, items: page.items.map(toSummary) };
  }

  async findByCode(code: string): Promise<Property | null> {
    return byCode.get(code) ?? null;
  }

  /**
   * Same city first, then same type, closest price. Keeps the visitor moving
   * instead of dead-ending on a listing that does not fit.
   */
  async findSimilar(property: Property, limit: number): Promise<readonly PropertySummary[]> {
    const operation: Operation = property.operations[0] ?? 'venda';
    const reference = priceFor(property.pricing, operation);

    const scored = CATALOG.filter(
      (candidate) =>
        candidate.code !== property.code &&
        candidate.operations.includes(operation) &&
        candidate.photos.length > 0,
    ).map((candidate) => {
      let score = 0;
      if (candidate.address.citySlug === property.address.citySlug) score += 4;
      if (candidate.address.neighborhoodSlug === property.address.neighborhoodSlug) score += 3;
      if (candidate.type === property.type) score += 3;
      const candidatePrice = priceFor(candidate.pricing, operation);
      if (reference !== null && candidatePrice !== null) {
        const delta = Math.abs(candidatePrice - reference) / reference;
        if (delta <= 0.25) score += 2;
        else if (delta <= 0.5) score += 1;
      }
      return { candidate, score };
    });

    return scored
      .filter((entry) => entry.score > 0)
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((entry) => toSummary(entry.candidate));
  }

  async featured(limit: number): Promise<readonly PropertySummary[]> {
    const ranked = [...CATALOG]
      .filter((property) => property.photos.length >= 4)
      .sort((a, b) => {
        if (a.isFeatured !== b.isFeatured) return a.isFeatured ? -1 : 1;
        if (a.isExclusive !== b.isExclusive) return a.isExclusive ? -1 : 1;
        return (b.pricing.salePrice ?? 0) - (a.pricing.salePrice ?? 0);
      });
    return ranked.slice(0, limit).map(toSummary);
  }

  async facets(operation: SearchQuery['operation']): Promise<CatalogFacets> {
    const pool = CATALOG.filter((property) => property.operations.includes(operation));

    const cityCounts = countBy(pool, (property) => property.address.citySlug);
    const cityNames = new Map(pool.map((p) => [p.address.citySlug, p.address.city]));
    const cities: CityFacet[] = [...cityCounts.entries()]
      .map(([slug, count]) => ({ slug, name: cityNames.get(slug) ?? slug, count }))
      .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, 'pt-BR'));

    const neighborhoodKey = (p: Property) =>
      `${p.address.citySlug}::${p.address.neighborhoodSlug}`;
    const neighborhoodCounts = countBy(pool, neighborhoodKey);
    const neighborhoodNames = new Map(
      pool.map((p) => [neighborhoodKey(p), p.address.neighborhood]),
    );
    const neighborhoods: NeighborhoodFacet[] = [...neighborhoodCounts.entries()]
      .map(([key, count]) => {
        const [citySlug, slug] = key.split('::');
        return { slug, citySlug, name: neighborhoodNames.get(key) ?? slug, count };
      })
      .filter((facet) => facet.slug.length > 0)
      .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, 'pt-BR'));

    const typeCounts = countBy(pool, (property) => property.type);
    const types: TypeFacet[] = [...typeCounts.entries()]
      .map(([type, count]) => ({ type: type as PropertyType, count }))
      .sort((a, b) => b.count - a.count);

    const features = [...new Set(pool.flatMap((property) => property.features))].sort(
      (a, b) => a.localeCompare(b, 'pt-BR'),
    );

    const prices = pool
      .map((property) => priceFor(property.pricing, operation))
      .filter((price): price is number => price !== null);

    return {
      cities,
      neighborhoods,
      types,
      features,
      priceRange: {
        min: prices.length > 0 ? Math.min(...prices) : 0,
        max: prices.length > 0 ? Math.max(...prices) : 0,
      },
      total: pool.length,
    };
  }

  async allSummaries(): Promise<readonly PropertySummary[]> {
    return CATALOG.map(toSummary);
  }
}

export const propertyRepository: PropertyRepository = new CatalogRepository();
